### ISSUE TITLE
[Information] If you get error at first run.

### ISSUE THREAD

**Issue by Its-Vichy** [dropout1337/Telegram-AdBot#1]
Hi, you are probably a noob and looking why you get error..

Just create `sessions` file in the `assets` folder, like the repo if you are not gay to :p

**Comment by dropout1337** [comment]
Thanks for that, seems I missed that in the upload 😄

**Comment by balluh** [comment]
2 skids in one issue. nice. love it.

**Comment by Its-Vichy** [comment]
Nobody care

**Comment by balluh** [comment]
u gonna close this issue?

**Comment by dropout1337** [comment]
Only 1 skid here buddy 😄
